---
name: Build k8s-operator
on: 
  workflow_dispatch:
  push:
    paths:
      - k8s-operator/**

env:
  IMAGE: gcp-symphony-operator

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add a directory to the PATH
        run: echo "/usr/bin" >> $GITHUB_PATH

      - name: Run Tests
        run: |
          cd k8s-operator
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv --python 3.12 --allow-existing
          source .venv/bin/activate
          uv pip install -e ".[dev]"
          pytest tests
  
  check-tags:
    name: Check Tags
    runs-on: ubuntu-24.04
    outputs:
      is_release: ${{ steps.check.outputs.is_release }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

  set-version:
    name: Set Version
    runs-on: ubuntu-24.04
    needs: check-tags
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - id: set_version
        run: |
          if [[ "${{ needs.check-tags.outputs.is_release }}" == "true" ]]; then
            VERSION=${GITHUB_REF_NAME#v}
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
            VERSION=1.0.0-build.${GITHUB_RUN_NUMBER}-${SHORT_SHA}
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build:
    name: Build 
    runs-on: ubuntu-24.04
    needs: [check-tags, set-version]
    env:
      VERSION: ${{ needs.set-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (Simulate multi-arch builds)
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: k8s-operator
          file: ./k8s-operator/Dockerfile
          platforms: linux/amd64
          push: false # NOTE: It's important to set push to false here to avoid pushing test images to the registry
          load: true
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: ${{ env.IMAGE }}:${{ env.VERSION }}
          outputs: type=docker, dest=${{runner.temp}}/k8s-operator.tar

      - name: Upload Docker image artifact for debugging
        uses: actions/upload-artifact@v4
        with:
          name: k8s-operator-image
          path: ${{runner.temp}}/k8s-operator.tar
          retention-days: 1


  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-24.04
    needs: [unit-tests, build, set-version]
    env:
      VERSION: ${{ needs.set-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: k8s-operator-image
          path: ${{ runner.temp }}

      - name: Check Downloaded artifact
        run: |
          if [ -f ${{ runner.temp }}/k8s-operator.tar ]; then
            echo "Docker image artifact downloaded successfully."
          else
            echo "Failed to download Docker image artifact." && exit 1
          fi

      - name: Load Docker image
        run: |
          docker load -i ${{ runner.temp }}/k8s-operator.tar
      
      - name: Run Integration Tests
        run: |
          echo "Running integration tests..."
      
      - name: Verify Docker image
        run: |
          if docker images ${{ env.IMAGE }}:${{ env.VERSION }} | grep -q ${{ env.IMAGE }}; then
            echo "Docker image ${{ env.IMAGE }}:${{ env.VERSION }} is available."
          else
            echo "Docker image ${{ env.IMAGE }}:${{ env.VERSION }} not found." && exit 1
          fi

      - name: Run export-manifests
        run: |
          docker run --rm ${{ env.IMAGE }}:${{ env.VERSION }} export-manifests > manifests.yaml

      - name: Create cluster
        uses:  helm/kind-action@v1 
        with:
          version: v0.17.0
          cluster_name: symphony-operator-test-cluster

      - name: Load Docker image into Kind cluster
        run: |
          kind load docker-image ${{ env.IMAGE }}:${{ env.VERSION }} --name symphony-operator-test-cluster

      - name: Run kind integration tests
        run: bash ./k8s-operator/tests/ci/run-kind-tests.sh

      - name: Upload manifests artifact for debugging
        uses: actions/upload-artifact@v4
        with:
          name: manifests.yaml
          path: manifests.yaml
          compression-level: 0

  push:
    name: Push to Registry
    needs: [integration-tests, check-tags, set-version]
    runs-on: ubuntu-24.04
    env:
      VERSION: ${{ needs.set-version.outputs.version }}
      REGISTRY: "gcp-symphony-registry" # TODO: Update with actual registry

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: k8s-operator-image
          path: ${{ runner.temp }}

      - name: Check Downloaded artifact
        run: |
          if [ -f ${{ runner.temp }}/k8s-operator.tar ]; then
            echo "Docker image artifact downloaded successfully."
          else
            echo "Failed to download Docker image artifact." && exit 1
          fi

      - name: Load Docker image
        run: |
          docker load -i ${{ runner.temp }}/k8s-operator.tar
        
      - name: Tag version image
        run: |
          docker tag ${{ env.IMAGE }}:${{ env.VERSION }} ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.VERSION }}
        
      - name: Push version image to registry
        run: |
          echo "Pushing image ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.VERSION }} to registry..."

      - name: Tag latest image
        if: needs.check-tags.outputs.is_release == 'true'
        run: |
          docker tag ${{ env.IMAGE }}:${{ env.VERSION }} ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
      
      - name: Push latest image to registry
        if: needs.check-tags.outputs.is_release == 'true'
        run: |
          echo "Pushing image ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest to registry..."